<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <AssemblyName>kagami</AssemblyName>
    <NoWarn>$(NoWarn);IL2026;IL3050</NoWarn>
  </PropertyGroup>

  <!-- Settings for trimmed/AOT deployment -->
  <PropertyGroup>
    <!-- Enable trimming and AOT analyzers and warnings and indicate that NuGet package is trim-compatible -->
    <IsAotCompatible>true</IsAotCompatible>
    <!-- Enable trimming-compatible configuration binding -->
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
  </PropertyGroup>

  <!-- NuGet properties -->
  <PropertyGroup>
    <PackageId>Summerdawn.Kagami</PackageId>
    <Description>Kagami is a CLI tool and daemon to import, export and synchronize contacts.</Description>
    <IsPackable>true</IsPackable>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>kagami</ToolCommandName>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Summerdawn.Kagami.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.0" />
    <PackageReference Include="System.CommandLine" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.Extensions.Logging" />
    <Using Include="Microsoft.Extensions.Options" />
  </ItemGroup>

</Project>
